### PR TITLE
SE-2946: Add support for Video and Problem library types.

### PR DESCRIPTION
**Pull request by Kelketek**
Adds support for library types, adding the 'video' and 'problem' type, and permitting filtering by these types.

**Discussions**: https://docs.google.com/document/d/1hRrSmWWlGHhi-bh9AIlpSuLtJFnn2GpavNe8OQxthbE/edit

**Dependencies**: https://github.com/edx/frontend-app-library-authoring/pull/7 must be merged first. This pull requests exists to make code review easier-- it is not the one to be merged.

**Screenshots**:

Creation page changes:

image

Edit Details:

image

Listing with filtering:

image

**Merge deadline**: This PR not to be merged-- it is only for code review.

**Testing instructions**:

1. Use the `edx-platform` branch `open-craft:library_types` on the backend.
1. Follow the directions in https://github.com/edx/frontend-app-library-authoring/pull/4 up until item 15.
1. Create a new library of each type.
1. Create blocks in the library. In complex and legacy libraries, you should be able to create many different types.
1. In Video and problem libraries, you should be able to only create blocks of their respective type.
1. For complex, video, and problem libraries, test conversion by going to the Details menu for the library and switching the type.
    * This should succeed if the library is empty always.
    * It should succeed if moving from video or problem to complex.
    * It should succeed if moving from complex to problem, or complex to video, when all blocks match their respective types.
    * It should fail if moving from complex to problem, or problem to complex, if all blocks don't match the target type.
1. You should be able to filter the libraries by type on the library listing page. 

**Reviewers**
- [x] @yekibud 
- [ ] edX reviewer[s] TBD

### CODE REVIEW

**Comment by yekibud** [comment]
@Kelketek adding a legacy library doesn't redirect to the video library component page (or update the list of created libraries or provide any feedback).  I assume that's not what is expected, correct?

**Comment by Kelketek** [comment]
I'm not sure what you mean-- what does a legacy library have to do with video components? Adding a legacy library SHOULD send you to the old studio on the CMS's port number, so you can continue from there.

**Comment by yekibud** [comment]
Your testing instructions say to "Create a new library of each type" - I guess this could have just meant the new types you added, but I decided to create a legacy type, as well, and found the behavior unexpected.  After creating a legacy library, the page did not attempt a redirect for me.  Is this working for you?

**Comment by Kelketek** [comment]
No-- it appears to have stopped working since I last looked at that part of the code. I'll fix it.

**Comment by yekibud** [comment]
Doesn't look like error handling for slugs is working properly.  This is what I get adding a slug with a space.

image

**Comment by Kelketek** [comment]
The slug handling is outside of the scope of this PR. I'm not sure where to report it, though.

**Comment by Kelketek** [comment]
Actually, maybe it isn't. Let me look closer.

**Comment by yekibud** [comment]
~~UI nit-pick:~~  [Correction, not just a nit-pick, because this also requires the user to deselect and reselect "Video" when changing from other lib types.] The library type selection box doesn't seem bound to the library's data (always shows the first item in the list - "Video", even if it's a "Problem" type).

image

**Comment by yekibud** [comment]
Seeing some strange/inconsistent behavior with deleting blocks from the new library types.  The redirect to the library/component view after deletion usually leaves the component block rendered on the page - but sometimes it properly removes it on redirect, but then the second time you create and delete a component, it will stay rendered.

image

**Comment by yekibud** [comment]
After triggering a library type switching error, such as from complex to problem when there are non-problem blocks (like html), that error persists after cancelling and returning to the detail page to attempt to change the library type again (even after removing the problematic block).
image

**Comment by Kelketek** [comment]
@yekibud I've pushed some changes. Here's what's changed (and what hasn't and why)

1. Error handling for incorrect slugs is not changed because that was a pre-existing bug and it will take some thought on how to fix it-- the error being thrown would need to be rendered on top of the slug and the error code handler assumes the error is flat, not field-bound.
2. I've fixed the issue with the default loading of the drop-down.
3. The issue with errors sticking around on that form turned out to be a pre-existing bug, but I fixed it anyway since figuring that out lead to the solution being fairly simple.
4. The issue with block addition/deletion is not resolved because it appears to be pre-existing. I didn't touch that code, but I've gotten the impression that there are some state management bugs that are laying around because there's not much code for making sure that old data is cleared out before navigating away, which can occasionally cause conflicts and was the cause of 3.
5. The redirect on addition of a legacy library is fixed.

**Comment by yekibud** [comment]
UI QA checks out @Kelketek :+1: 

Should we verify/report all the other pre-existing defects?

Moving on to look at the code now.

Btw, I think you need to update your `.git/config` email - currently showing fox@artconomy.com.

**Comment by yekibud** [comment]
:+1:

- [x] I tested this: (describe what you tested) - see above
- [x] I read through the code
- [ ] I checked for accessibility issues
- [ ] Includes documentation
- [ ] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository

**Comment by Kelketek** [comment]
@yekibud I think you should probably just create a ticket for these bug issues and put it in the next sprint. These things will need to get fixed anyway, and while @arbrandes is off on vacation, I don't think he'll mind too much if we handle this while he's out.

**Comment by Kelketek** [comment]
@bradenmacdonald I've been told you'd be the person to verify that the above statement is correct. :)

**Comment by Kelketek** [comment]
Also, @yekibud Please make sure to copy your thumbs up over to the other copy of this PR upstream.

**Comment by bradenmacdonald** [comment]
@Kelketek Sounds good, yes I'm sure it makes sense to fix bugs sooner rather than later. BTW please document known issues via *both* a Jira ticket and a mention in the README at https://github.com/edx/frontend-app-library-authoring#known-issues - so that edX and others testing this out know that bugs we're aware of.

**Comment by Kelketek** [comment]
@yekibud I've added the known issues to the README. Could you please create the tickets with reproduction instructions and slate them in the next sprint? If you want them, go ahead and take them, otherwise you can assign them to me and mark yourself as the reviewer.

**Comment by yekibud** [comment]
Created [SE-3231](https://tasks.opencraft.com/browse/SE-3231) and [SE-3230](https://tasks.opencraft.com/browse/SE-3230) and assigned to myself in the next sprint.

**Comment by Kelketek** [comment]
Closing this version as upstream is now up to date with master.

**Pull request closed without merging**
